### ISSUE TITLE
Port 0 or '?' not working on OS X

### ISSUE THREAD

**Issue by kibin** [gruntjs/grunt-contrib-connect#103]
When I'm trying to set port to special values (e.g. 0 or '?') grunt exits with
`Fatal error: Port should be > 0 and < 65536`
On colleague's Ubuntu it seems to working okay.

What might be the problem?
I'm on OS X 10.9.2, grunt 0.4.4, grunt-contrib-connect 0.7.1

**Comment by jeffreydwalter** [comment]
I'm seeing this issue in node v0.12.0.

**Comment by quentindemetz** [comment]
Same issue here. @vladikoff do you want me to create a new ticket ?

**Comment by jeffreydwalter** [comment]
@quentindemetz I already filed an issue for this bug in the node project and they are working on the fix.

https://github.com/joyent/node/issues/9194

**Comment by quentindemetz** [comment]
Thanks, fantastic! Looks as if it's been fixed, we just need to wait for a new release…
