### ISSUE TITLE
Relative URL path

### ISSUE THREAD

**Issue by brunowego** [gruntjs/grunt-contrib-connect#140]
Have any way for href's and src's include the relative URL path?

Example:

/index.html
/users/list.html

Thanks!

**Comment by landed1** [comment]
I might have the same issue - it seems the javascript is added at folder level
http://localhost:8000/
but no longer there if I visit 
http://localhost:8000/blogpage.html

Is that what you mean ?

**Comment by landed1** [comment]
My issue was that I had not provided sufficient html for the live reload script to be bound to..

**Comment by landed1** [comment]
Here is how I am using it - https://github.com/landed1/cambs.eu

**Comment by brunowego** [comment]
My way to solve it is:

In wiredep task rewrite output of script and style:

```js
wiredep: {
  app: {
    fileTypes: {
      html: {
        block: /(([ \t]*)<!--\s*bower:*(\S*)\s*-->)(\n|\r|.)*?(<!--\s*endbower\s*-->)/gi,
        detect: {
          js: /<script.*src=['"]([^'"]+)/gi,
          css: /<link.*href=['"]([^'"]+)/gi
        },
        replace: {
          js: '<script src="/{{filePath}}"></script>',
          css: '<link rel="stylesheet" href="/{{filePath}}">'
        }
      }
    }
  }
}
```

And in html add slash before call:

```html
<!-- build:js(.) /scripts/vendor.js -->
<!-- bower:js -->
<script src="/bower_components/jquery/dist/jquery.js"></script>
<!-- endbower -->
<!-- endbuild -->
```
