### ISSUE TITLE
Server does not follow symlinks

### ISSUE THREAD

**Issue by domoritz** [gruntjs/grunt-contrib-connect#155]
I would like to symlink a library from another directory but the server does not symlink so I have to copy the file.

**Comment by richardbatty** [comment]
Does anyone have an idea of how to solve this? It makes it impossible to test local bower components by symlinking to them.

**Comment by richardbatty** [comment]
It actually wasn't a problem with grunt-contrib-connect, it was a problem with wiredep. Wiredep isn't following the symlink so it isn't inserting the script tag for the bower component into index.html.
