### ISSUE TITLE
Allow combining global and task middleware

### ISSUE THREAD

**Issue by LaurentGoderre** [gruntjs/grunt-contrib-connect#160]
Currently, if there is a global middleware sett and task specific one, the task specific overwrites the middleware instead of adding to the global one. Would it be possible to allow global and task specific middleware to co-exist?

**Comment by LaurentGoderre** [comment]
I have a feeling that it's not possible because of the way grunt works....

**Comment by sindresorhus** [comment]
> I have a feeling that it's not possible because of the way grunt works....

That's correct. You can easily have the global array in a variable though and reuse it in the target options. It's just JS after all.

**Comment by LaurentGoderre** [comment]
Yeah good point...the fact that ours is coffee is distracting me
