### ISSUE TITLE
Failures with node.js >= 0.12?

### ISSUE THREAD

**Issue by XhmikosR** [gruntjs/grunt-contrib-connect#168]
Apparently tests fail for the custom `port` options `0` and `?`.

/CC @sindresorhus

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-connect/issues/166

**Comment by timkendrick** [comment]
I submitted a pull request to fix this, so this works as of 7c7e47e (merged into master).

@sindresorhus, are you able to push an npm release so that we can use grunt-contrib-connect with Node 0.12?
