### ISSUE TITLE
options.hostname not working?

### ISSUE THREAD

**Issue by goodpixels** [gruntjs/grunt-contrib-connect#169]
I'm trying to `grunt-contrib-connect` to create a server under a specific URL, let's say `http://my.website/`. According to the documentation, all I need to do is just to change the `hostname` option, but I keep getting an error saying: `Fatal error: getaddrinfo ENOTFOUND my.website`.

Here's my `gruntfile.js`:

```
connect: {

    dev: {

        options: {

            keepalive:  true,
            port:       80,
            hostname:   'my.website',
            base:       'public'

        }

    }

},
```

Thanks.

**Comment by timkendrick** [comment]
My understanding is that the `hostname` option is used to say "deny all connections that do not use this hostname to access the server". Importantly, it doesn't actually set up the route that redirects `my.website` to `127.0.0.1` – this has to be done elsewhere.

In your case, I think the simplest solution would be to add an entry in your `HOSTS` file that routes `my.website` to `127.0.0.1`
