### ISSUE TITLE
Change default hostname, Chrome won't access http://0.0.0.0:*/

### ISSUE THREAD

**Issue by ricobl** [gruntjs/grunt-contrib-connect#181]
Recent Chrome versions won't access hostnames with "0.0.0.0", it will search instead.

It would be nice to change the default hostname.

Here is a question on Super User pointing that it is a non-routable meta-address used to designate an invalid, unknown or non applicable target:

http://superuser.com/questions/846721/chrome-wont-access-http-0-0-0-04200

**Comment by xpavp03** [comment]
We currently detect 0.0.0.0 and open localhost instead.
https://github.com/gruntjs/grunt-contrib-connect/blob/master/tasks/connect.js#L204

Also, hostname can be changed via Gruntfile.js
```javascript
connect: {
  options: {
    hostname: 'localhost'
```
This ticket can be closed.
