### ISSUE TITLE
Livereload breaks the middleware

### ISSUE THREAD

**Issue by lnfnunes** [gruntjs/grunt-contrib-connect#185]
I'm using [compression](https://github.com/expressjs/compression) package for gzip my responses.
It works fine if _livereload_ options is "false".
When I turn it on the middleware stops working and the browser has blank responses from server (no page).
Bellow is my middleware configuration:

``` javascript
server: {
  options: {
    port: 8000,
    livereload: false,
    keepalive: false,
    middleware : function(connect, options, middlewares) {
      // Some bug if ivereload is enabled !!!
      if (!options.livereload) {
        middlewares.unshift(compression());
      }
      return middlewares;
    }
}
```

**Comment by ambodi** [comment]
I'm getting the same when I am trying to set `Access-Control-Allow-Origin` in the request header.

**Comment by chhaymenghong** [comment]
@lnfnunes try the following:
- get rid of livereload
- npm install connect-livereload --save-dev
- add middlewares in the following order:
`middleware: function (connect, options, middlewares) {
            middlewares.unshift(
require('grunt-middleware-proxy/lib/Utils').getProxyMiddleware(), // get rid of this if you are not using proxy
 compression(),
 require('connect-livereload')())
        
            return middlewares;
          }`

**Comment by lnfnunes** [comment]
Thanks in advance!
Unfornutly, nowadays I don't have this scenario anymore so I can't confirm if this works or not. Thanks for you reply @chhaymenghong!
