### ISSUE TITLE
Incorrect https://github.com/gruntjs/grunt-contrib-connect#roll-your-own after upgrade

### ISSUE THREAD

**Issue by SamuraiPrinciple** [gruntjs/grunt-contrib-connect#189]
Greetings,

I believe that the instructions in:

https://github.com/gruntjs/grunt-contrib-connect#roll-your-own

are no longer valid since version v0.11.0. I believe:

connect(connect.static('www-root')).listen(9001);

should be replaced with (once serve-static is added to packages.json):

serveStatic = require('serve-static');
connect(serveStatic('www-root')).listen(9001);

Or maybe there's a better solution?

**Comment by jjosef** [comment]
+1 is there a reason this was removed? It totally breaks typical Gruntfiles

**Comment by vladikoff** [comment]
@SamuraiPrinciple thanks for the issue. fixed in v0.11.2
