### ISSUE TITLE
connect.static is undefined after update

### ISSUE THREAD

**Issue by paveleremin** [gruntjs/grunt-contrib-connect#191]
After update "grunt-contrib-connect" from ^0.7.1 to ^0.11.2, my code is broken:
```
connect: {
    options: {
        port: 9000,
        // Change this to '0.0.0.0' to access the server from outside.
        hostname: 'localhost',
        livereload: 35729
    },
    livereload: {
        options: {
            open: true,
            middleware: function (connect){
                var modRewrite = require('connect-modrewrite');

                return [
                    modRewrite(['^[^\\.]*$ /index.html [L]']),
                    connect.static('.tmp'),
                    connect().use(
                        '/bower_components',
                        connect.static('./bower_components')
                    ),
                    connect.static(appConfig.app)
                ];
            }
        }
    },
```
now connect.static is undefined. Is it correct?

**Comment by vladikoff** [comment]
we updated to connect 3, there is no connect.static anymore, see https://github.com/gruntjs/grunt-contrib-connect#roll-your-own

**Comment by eddiemonge** [comment]
That really isn't much of a migration path.

Connect 3 no longer uses `connect.static`. Similar functionality is available using `serve-static`. To use this:

 * Add `serve-static` as a dependency in your project (or dev, basically alongside your `grunt-contrib-connect` dependency): `npm install --save serve-static`
 * Require the module in your Gruntfile: `var serveStatic = require('serve-static');`
 * Change your `connect.static` references to `serveStatic`.

```
            return [
                modRewrite(['^[^\\.]*$ /index.html [L]']),
                serveStatic('.tmp'),
                connect().use(
                    '/bower_components',
                    serveStatic('./bower_components')
                ),
                serveStatic(appConfig.app)
            ];
````

**Comment by pgrodrigues** [comment]
Thanks @eddiemonge.

**Comment by spdaly** [comment]
Thanks @eddiemonge

**Comment by frazras** [comment]
Does anyone get:
    
    TypeError: object is not a function
 
for 

    connect().use(
                        '/bower_components',
                        connect.static('./bower_components')
                    ),

Im confused how it worked in the first place because in 
`connect.static('.tmp'),` was used here as an object then right after `connect().use(` is used as a function

**Comment by Chris2011** [comment]
I use serverStatic too and it works like a charme, what doesn't work is this:

```js
...
// Make directory browse-able.
var directory = options.directory || options.base[options.base.length - 1];
middlewares.push(connect.directory(directory));
return middlewares;
...
```

connect.directory is not a function, is the error message, the same as for .static. How can I fix that? Couldn't find a solution.

**Comment by overmedia** [comment]
If is not backwards compatible I think that version number should be changed to 1.[something].[something]. Read this:
version [Major].[Minor].[Patch]
Major = “breaking changes” – Increment MAJOR version when you have removed or changed a feature, and dependent modules will have to modified to be compatible with the new version.

Minor = “new feature” – Increment MINOR version when you have added a feature, but the module is backwards compatible.

Patch = “bugfix” – Increment PATCH version when you have fixed a problem, but not broken or changed anything else.

source: http://developer.telerik.com/featured/mystical-magical-semver-ranges-used-npm-bower/

**Comment by sterichards** [comment]
> return [
>                 modRewrite(['^[^\\.]*$ /index.html [L]']),
>                 connect.static('.tmp'),
>                 connect().use(
>                     '/bower_components',
>                     connect.static('./bower_components')
>                 ),
>                 connect.static(appConfig.app)
>             ];

**Comment by sterichards** [comment]
I've found the best solution to be roll-back

Spent 2 hours trying various suggested changes and nothing works.

Rolled back and it works like a charm
