### ISSUE TITLE
Is there any way to start this task without cannibalizing the network port?

### ISSUE THREAD

**Issue by mfidemraizer** [gruntjs/grunt-contrib-connect#210]
For example, let's say I've another application on port 80 and I'd like to run `connect` on the same port.

Is this possible?

Thank you in advance!

**Comment by wizzyfx** [comment]
Nope, it's not possible. Only a single web server can bind on a port per IP address. It may be possible by running a proxy server (on port 80) but it will be a pain to configure and you will still have to run each server on a different port.

**Comment by mfidemraizer** [comment]
Uhmm, ok. I guess that since `connect` goal isn't being a complete Web server, it doesn't support this. BTW it would be very useful.

Thanks anyway for the effort.
