### ISSUE TITLE
grunt-contrib-connect Incompatible with NPM Registry; requires direct internet connection

### ISSUE THREAD

**Issue by jamiewastin** [gruntjs/grunt-contrib-connect#216]
Commit 81d17a3 introduced a hard-coded dependency on a git URL `package.json`:

    "http2": "https://github.com/gruntjs/node-http2#fix-return-value"

This is breaking builds in an enterprise setting where NPM has been configured to use a private / proxy registry, and is unable to access the web directly.

The fixes from this fork need pushing upstream, or they should be published independently as a module in their own right.

**Comment by JoniJnm** [comment]
The commit is 79ef3c21d9068cbf8d5ee2d1ef4c7c69a0585076

Should it be: `git+https://github.com/gruntjs/node-http2#fix-return-value`?

**Comment by jamiewastin** [comment]
@JoniJnm - No, that would be no better. Referencing `github.com` with any protocol is a bad idea.

In my specific scenario, which I imagine is common amongst large organizations, there is simply no internet connection between the build machine and the internet.

**Comment by vladikoff** [comment]
Should be fixed in 1.0.2
