### ISSUE TITLE
Doesn't work with portscanner@1.1.0

### ISSUE THREAD

**Issue by alippai** [gruntjs/grunt-contrib-connect#224]
The latest portscanner release breaks the current grunt-contrib-connect version:
https://github.com/baalexander/node-portscanner/issues/49

**Comment by philtim** [comment]
portscanner@1.1.0 now checks whether the port number is a number, string, or function and handles each type differently. In our case it was sufficient to change the port number from a string into a number.

**Comment by XhmikosR** [comment]
Seems to be fixed upstream.
