### ISSUE TITLE
This project's build is currently broken.

### ISSUE THREAD

**Issue by aknrdureegaesr** [gruntjs/grunt-contrib-connect#248]
I entered a PR that ran into a broken build. I assume that the build breakage is unrelated to my change. To test that theory, I opened another PR, namely, #247, that contains only one empty commit (a commit that does not change anything). Sure enough: That build broke as well.

Kindly fix the build, and then preferably retrigger the build on all open pull requests.

I'm happy to have #247 been thrown away once no longer needed.

**Comment by XhmikosR** [comment]
Fixed.
