### ISSUE TITLE
Connect cannot start on any port - EADDRNOTAVAIL

### ISSUE THREAD

**Issue by netpoetica** [gruntjs/grunt-contrib-connect#25]
```
➜  sample-simple-app git:(master) ✗ grunt
Running "connect:server:keepalive" (connect) task
Starting connect web server on localhost:9190.
Waiting forever...
Fatal error: listen EADDRNOTAVAIL
```

I am continually getting this error even when I change the port to 8000, 8080, 9001, etc. I have tried sudo killall node and I have run "ps aux | grep node" and I do not have any node processes running. I have also checked netstart and do not have anything running on those ports.

It appears that somehow grunt or connect is persisting this server? I have keepalive on there, but I usually terminate the process with Control + C. Yesterday, it would sometimes work and sometimes give me this error, but now I get it all the time.

Here's the Gruntfile

```
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    connect: {
      server: {
        options: {
          port: 9190,
          keepalive: false,
        }
      }
    },
    uglify: {
      options: {
        banner: '/*! <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd") %> */\n'
      },
      build: {
        src: 'src/<%= pkg.name %>.js',
        dest: 'build/<%= pkg.name %>.min.js'
      }
    },
    jasmine: {
      test: {
        src: 'app/**/*.js',
        options: {
          specs: 'test/*.spec.js',
          helpers: 'test/*.helper.js',
          host: 'http://127.0.0.1:8080'
        }
      }
    }
  });

  // A basic server for testing the app - this server only runs while grunt is running. Use keepalive: true for use as a development server
  grunt.loadNpmTasks('grunt-contrib-connect');

  // Load the plugin for Jasmine bdd testing
  grunt.loadNpmTasks('grunt-contrib-jasmine');

  // Load the plugin that provides the "uglify" task.
  grunt.loadNpmTasks('grunt-contrib-uglify');

  // Default task(s).
  grunt.registerTask('default', ['connect:server:keepalive']);
  grunt.registerTask('test', ['connect:server', 'jasmine:test']);

};
```

I'm on Mac OSX Mountain Lion (UNIX) and I have node 0.8.15, grunt-cli v0.1.7, grunt v0.4.1.

**Comment by mtsweir** [comment]
I may have had a similar issue on my local server at home, I ran ipconfig and figured my IP address was somehow different to what it had always been.

**Comment by prayagupd** [comment]
Weird, setting permission `777` on kibana-5.3.0 works.

**Comment by sahan91** [comment]
I had the same issue and I had a different IP address other than 127.0.0.1 on my webpack.config.js file. (Yes, it has got updated from a commit from another developer!)

Updated the devServer host like so:

```
devServer: {
        port: 8081,
        host: '127.0.0.1',
}
```

**Comment by tengontheway** [comment]
in macOS，you should modify `sudo vim /etc/hosts/`  
```
127.0.0.1  localhost
```

**Comment by agroves333** [comment]
> sudo vim /etc/hosts/
should be
`sudo vim /etc/hosts`

**Comment by Joseph2009** [comment]
facing this issue:

listen EADDRNOTAVAIL: address not available 192.168.7.63:4200 Error: listen EADDRNOTAVAIL: address not available 192.168.7.63:4200 at Server.setupListenHandle [as _listen2] (net.js:1253:19) at listenInCluster (net.js:1318:12) at GetAddrInfoReqWrap.doListen [as callback] (net.js:1451:7) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)

here are the version details:
Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package Version
@angular-devkit/architect 0.13.9
@angular-devkit/build-angular 0.13.9
@angular-devkit/build-optimizer 0.13.9
@angular-devkit/build-webpack 0.13.9
@angular-devkit/core 7.3.9
@angular-devkit/schematics 7.3.9
@angular/cdk 7.3.7
@angular/cli 7.3.9
@angular/material 7.3.7
@ngtools/webpack 7.3.9
@schematics/angular 7.3.9https://discourse.nodered.org/t/error-listen-eaddrnotavail-address-not-available-1-1-1-1-10502/7627
@schematics/update 0.13.9
rxjs 6.5.2
typescript 3.2.4
webpack 4.29.0

please someone help me... Thanks

**Comment by YummyTastyCode** [comment]
I got the same problem for python + VSCode debug.
As for me, the problem was about the Cisco VPN connection. This somehow changes network properties. So, when you disable VPN all properly works.
I wrote here because this is the first googled link.

**Comment by daksh23** [comment]
> set default address ==> 127.0.0.1

**Comment by TopScrech** [comment]
restarting my Mac fixed the issue
