### ISSUE TITLE
`node-http2` is deprecated. Use node's built in `http2`

### ISSUE THREAD

**Issue by darcyparker** [gruntjs/grunt-contrib-connect#270]
https://www.npmjs.com/package/node-http2 points to https://github.com/kaazing/node-http2 which no long exists.

It originally forked https://github.com/molnarg/node-http2, which notes that as of Node v9, the built in `http2` can be used.

**Comment by darcyparker** [comment]
Looks like this is a duplicate of https://github.com/gruntjs/grunt-contrib-connect/issues/268, but it is not obvious by the title.

**Comment by pedrosanta** [comment]
> Looks like this is a duplicate of #268, but it is not obvious by the title.

Yhea @darcyparker, the issue started as the vulnerability report and then shifted focus. This line of action is more succinct. I'll close that one and let's join efforts on this one.

Checking #268 for context about the vulnerability is still worthwhile.

**Comment by pedrosanta** [comment]
Also, as I state on my comment (https://github.com/gruntjs/grunt-contrib-connect/issues/268#issuecomment-903302596) updating to node `http2` requires a new major version (it's a breaking change on the engines version supported).

**Comment by pedrosanta** [comment]
@Krinkle Hello, with the `4.0.0` release and the Node engines/version update (>=16), maybe we can consider, revisit this?

**Comment by Krinkle** [comment]
@pedrosanta Yes! I don't use the http2 feature myself, but I'd be open to reviewing a pull request if you've got something in mind.

**Comment by pedrosanta** [comment]
Sure, will post one then, whenever I can. Cheers.
