### ISSUE TITLE
Fix vulnerability from websocket dependency: Denial of Service

### ISSUE THREAD

**Issue by gaurav517** [gruntjs/grunt-contrib-connect#271]
Current dependency version for websocket is vulnerable to regular expression denial of service.
![image](https://user-images.githubusercontent.com/15346341/133963681-c609731c-275e-44ee-98a6-be7d225ab1a4.png)

**Comment by gaurav517** [comment]
websocket vulnerability is fixed in https://github.com/websockets/ws/commit/00c425ec77993773d823f018f64a5c44e17023ff

**Comment by mhassan1** [comment]
This should be resolved by https://github.com/gruntjs/grunt-contrib-connect/pull/289.
