### ISSUE TITLE
Is it possible to configure the mime type returned by grunt-contrib-connect?

### ISSUE THREAD

**Issue by DanKaplanSES** [gruntjs/grunt-contrib-connect#48]
I have a specific file in my app that I need to return as a mime type of `text/cache-manifest`.  The rest should be served just like [grunt-contrib-connect](https://github.com/gruntjs/grunt-contrib-connect) normally does.  Is it possible to configure grunt-contrib-connect this way?  If I had to guess, it would have something to do with the [middleware](https://github.com/gruntjs/grunt-contrib-connect/blob/master/test/connect_test.js) but I don't see an example of how to do this.  

If anyone cares why I need this, it's because I've got a static html5 webapp, and I need to force it to be cached on my iPad.  To do that, I need to follow these directions: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/Client-SideStorage/Client-SideStorage.html

If this is already possible, I'm requesting documentation.  If it's not possible, I'm requesting this feature.  Thanks

**Comment by Stefany93** [comment]
I have the same problem, I need to serve files without extension as text/html
