### ISSUE TITLE
Change default IP from "localhost" to "0.0.0.0"

### ISSUE THREAD

**Issue by cowboy** [gruntjs/grunt-contrib-connect#60]
By specifying `0.0.0.0`, the server will bind to all IPs, allowing both "localhost" to continue to work (locally) as well as allowing the server to be accessed from external devices via the machine's IP or hostname.

Will this cause any problems? We would have to bump the minor version, but this change is awesome in my testing, here.

Any downsides?

**Comment by rienheuver** [comment]
On my windows 8.1 machine, this actually breaks something for me. 0.0.0.0:35729 will not access the livereload-server. Somehow 0.0.0.0 doesn't look at my machine at all (0.0.0.0:8000 gives an address invalid too).

**Comment by vatsalpande** [comment]
I am running windows 8 and if I change it to 0.0.0.0 it starts to look for ip address 0.0.0.0 and hence starts giving error

**Comment by piotr-dobrogost** [comment]
You can't connect with address 0.0.0.0 on Windows – http://stackoverflow.com/a/28230165/95735 Use *localhost* or address 127.0.0.1 instead when connecting.
