### ISSUE TITLE
How would i get the server to redirect all the urls to index.html

### ISSUE THREAD

**Issue by benedikt-buchert** [gruntjs/grunt-contrib-connect#66]
I want the server to redirect all urls to index.html, because I'm using the html 5 history api. Is there an elegant way to do this with connect?

**Comment by DominikDitoIvosevic** [comment]
I got Warning: connect.static is not a function Use --force to continue.
Any ideas?

**Comment by vladikoff** [comment]
@DominikDitoIvosevic see https://github.com/gruntjs/grunt-contrib-connect/issues/191#issuecomment-144513829

**Comment by DominikDitoIvosevic** [comment]
Yeah. This seems to be working for me tho


    connect: {
      server: {
        options: {
          port: 9001,
          base: '',
          keepalive: true,
          // http://danburzo.ro/grunt/chapters/server/
          middleware: function(connect, options, middlewares) {
            // 1. mod-rewrite behavior
            var rules = [
                '!\\.html|\\.js|\\.css|\\.svg|\\.jp(e?)g|\\.png|\\.gif$ /index.html'
            ];
            middlewares.unshift(rewrite(rules));
            return middlewares;
          }
        }
      }
    }

**Comment by camsjams** [comment]
@DominikDitoIvosevic that's a simple fix - it's just a dev server to me, didn't want to go through too much hassle

**Comment by tandn37** [comment]
nice solution guys
