### ISSUE TITLE
Is POST supported?

### ISSUE THREAD

**Issue by LostSenSS** [gruntjs/grunt-contrib-connect#97]
Hi! 
Why POST request can not work? 
Example : I send simple form on current page address.
Output in Grunt console :
`[D] server POST /build/views/profile.html 404 - - 1 ms`
With GET all fine: 
`D] server GET /build/views/profile.html?name=test 200 8960 - 1 ms`
If I try to do the same on real server then all right.

**Comment by mturnwall** [comment]
I'm getting 405 error as well. I'm on the latest version, v1.0.2. I have middleware setup set the headers to allow POST but I still get the error. This makes it very hard to test since I can test my changes locally.

```js
server: {
    options: {
        base: ['<%= config.dev %>', '<%= config.app %>'],
        open: true,
        middleware: function (connect, options, middlewares) {
            middlewares.unshift(function (req, res, next) {
                res.setHeader('Access-Control-Allow-Origin', '*');
                res.setHeader('Access-Control-Allow-Credentials', true);
                res.setHeader('Access-Control-Allow-Methods', '*');
                res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

                return next();
            });
            return middlewares;
        }
    }
}
```

**Comment by dylanmensaert** [comment]
I try to enable CORS via middleware option by adding extra headers to the response. My code for this is:

```
                    middleware: function (connect, options, middlewares) {
                        middlewares.unshift(function(req, res, next) {
                            res.setHeader('Access-Control-Allow-Origin', '*');
                            res.setHeader('Access-Control-Allow-Methods', '*');

                            return next();
                        });

                        return middlewares;
                    }
```

 This works correctly, but an extra header is being added also which makes the response invalid. The header being added is `Allow: GET, HEAD, OPTIONS`.
Which also gives me code **405**.

I tried to add code to the unshift method to remove this header, namely `res.removeHeader('Allow');`, but it does not seem to work.

Any suggestions?
